"""Sweep timer entry: global root upkeep, new-project detection, and batch
catch-up syncs."""

import concurrent.futures
import json
import os
import subprocess
import sys
import time

from memd.config import (CLAUDE_PROJECTS_DIR, CURSORS_PATH, HOME, META_PATH,
                         atomic_write, git_toplevel, load_json, log,
                         save_config)
from memd.inbox import collect_inbox
from memd.memory import (enforce_budget_mistakes, find_project,
                         git_commit_memory, register, scaffold,
                         init_memory_repo)
from memd.sync import source_pending, sync_project, transcript_files

def write_global_index(cfg):
    """Regenerate <global>/.memory/projects.md — a GENERATED map of every
    registered project's memory root, derived from the live registry + last
    distill meta. Refreshed each sweep, so it can never drift the way curated
    prose would. It is NOT one of the curator's four files: the curator never
    reads or edits it, and durable cross-project truth still belongs in
    state.md / decisions.md. Returns True if the file changed."""
    gr = cfg.get("global_root")
    if not gr:
        return False
    mem = os.path.join(os.path.realpath(gr), ".memory")
    if not os.path.isdir(mem):
        return False
    meta = load_json(META_PATH, {})
    lines = [
        "# Project Memory Index",
        "",
        "_Auto-generated by memd from the project registry on each sweep. Do not",
        "edit by hand — it is overwritten. The curator does not read this file;",
        "durable cross-project truth belongs in state.md / decisions.md._",
        "",
    ]
    rows = 0
    for path, entry in sorted(cfg["projects"].items()):
        if entry.get("global"):
            continue
        m = meta.get(path, {})
        summary = " ".join((m.get("summary") or "").split())
        if len(summary) > 160:
            summary = summary[:157] + "..."
        last = m.get("last_sync", "never")
        lines.append(f"- **{entry.get('name', os.path.basename(path))}** — "
                     f"`{path}/.memory/`  (last distill: {last})")
        if summary:
            lines.append(f"  - {summary}")
        rows += 1
    if rows == 0:
        lines.append("_No projects registered._")
    body = "\n".join(lines) + "\n"
    out = os.path.join(mem, "projects.md")
    if os.path.exists(out) and open(out).read() == body:
        return False
    atomic_write(out, body)
    return True


def ensure_global(cfg):
    """Idempotently scaffold + register the global memory root (store: ~/.memory).

    The global root is a project entry flagged "global": its .memory holds
    system/user/cross-project truth. It is excluded from find_project()'s
    prefix matching (so it never shadows a real project or blocks new-project
    auto-scaffolding) and instead serves as the explicit fallback for sessions
    that belong to no project. Cheap no-op once registered (the common path)."""
    gr = cfg.get("global_root")
    if not gr:
        return None
    gr = os.path.realpath(gr)
    if cfg["projects"].get(gr, {}).get("global"):
        return gr
    scaffold(gr, name="global", model_stub=False)
    mem = os.path.join(gr, ".memory")
    write_global_index(cfg)  # generate the project map into the seed commit
    # Give the global store its own git history. Gate on .memory/.git directly
    # (not git_toplevel(mem)) so a git repo at $HOME can't make this think
    # ~/.memory is already versioned and skip its standalone init.
    if cfg.get("git_commit") and not os.path.isdir(os.path.join(mem, ".git")):
        init_memory_repo(mem, "memd: seed global memory root")
    # Preserve any pre-existing entry (custom name/extra_sources); just flag it.
    entry = cfg["projects"].get(gr) or {"name": "global", "extra_sources": []}
    entry["global"] = True
    cfg["projects"][gr] = entry
    save_config(cfg)
    log(f"initialized global memory root at {mem}")
    return gr
# --------------------------------------------------------------------------
# sweep (timer entry): missed sessions, inbox, auto-detect, prune
# --------------------------------------------------------------------------


def detect_new_projects(cfg):
    """Find git-root projects with recent claude sessions but no registration."""
    import glob as _glob
    found = set()
    cutoff = time.time() - 30 * 86400
    for jl in _glob.glob(os.path.join(CLAUDE_PROJECTS_DIR, "*", "*.jsonl")):
        try:
            if os.path.getmtime(jl) < cutoff:
                continue
            with open(jl) as f:
                for line in f:
                    try:
                        cwd = json.loads(line).get("cwd")
                    except json.JSONDecodeError:
                        continue
                    if cwd:
                        found.add(os.path.realpath(cwd))
                        break
        except OSError:
            continue
    new = []
    for cwd in found:
        if not os.path.isdir(cwd) or cwd in cfg["exclude"]:
            continue
        top = git_toplevel(cwd)
        if not top or top in cfg["exclude"] or top == HOME:
            continue
        if find_project(cfg, top) is None:
            new.append(top)
    return sorted(set(new))


def _sweep_one(cfg, path, entry, cursors, quiet, now):
    """Sweep a single project. Returns sync_project's True/None/False when a
    distill was attempted, or "idle" when there was nothing pending (budget
    enforcement only)."""
    pending = False
    for src in transcript_files(cfg, path):
        try:
            if source_pending(src, cursors) \
                    and now - os.path.getmtime(src) > quiet:
                pending = True
                break
        except OSError:
            continue
    if not pending and collect_inbox(path)[0]:
        pending = True
    if pending:
        return sync_project(cfg, path, trigger="sweep")
    enforce_budget_mistakes(path, entry["name"], cfg["budgets"]["mistakes.md"])
    return "idle"


def cmd_sweep(cfg, jobs=None):
    """Timer entry. Returns the number of failed distills (0 = clean sweep).

    Projects are swept in a thread pool (`--jobs` / config `sweep_jobs`,
    default 4) — the work is subprocess/IO bound, so threads suffice."""
    failed = 0
    ensure_global(cfg)
    if cfg["auto_scaffold"]:
        for path in detect_new_projects(cfg):
            scaffold(path)
            register(cfg, path)
            log(f"sweep: auto-scaffolded + registered {path}")
    cursors = load_json(CURSORS_PATH, {})
    quiet = cfg["quiet_seconds"]
    now = time.time()
    projects = [(p, e) for p, e in sorted(cfg["projects"].items())
                if os.path.isdir(p)]
    jobs = max(1, jobs or cfg.get("sweep_jobs", 4))
    # Parallelism is safe across DIFFERENT projects only, and that is all the
    # pool does: sync_project() takes a per-project flock (a same-project
    # overlap no-ops as "locked"), and the shared cursor/meta registries are
    # merged under the state lock by update_json().
    done, total = 0, len(projects)
    with concurrent.futures.ThreadPoolExecutor(max_workers=jobs) as pool:
        futures = {pool.submit(_sweep_one, cfg, p, e, cursors, quiet, now):
                   (p, e) for p, e in projects}
        for fut in concurrent.futures.as_completed(futures):
            path, entry = futures[fut]
            done += 1
            try:
                res = fut.result()
            except Exception as e:  # a worker crash must not kill the sweep
                log(f"sweep worker failed for {path}: {e}")
                failed += 1
                print(f"[{done}/{total}] syncing {entry['name']}... FAILED ({e})",
                      file=sys.stderr)
                continue
            if res is False:
                failed += 1
            outcome = {True: "done (distilled)", False: "FAILED distill",
                       None: "done (nothing new)"}.get(res, "done (idle)")
            print(f"[{done}/{total}] syncing {entry['name']}... {outcome}",
                  file=sys.stderr)
    # Refresh the generated project index in the global store (commit only if it
    # actually changed, to avoid churn on idle sweeps).
    if write_global_index(cfg):
        git_commit_memory(cfg.get("global_root"), "memd: refresh project index")
    log(f"sweep complete ({failed} failed distill(s))" if failed else "sweep complete")
    return failed
